spring:
  application:
    name: mybatis-helper-boot-starter-test-mp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///field_encrypt?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456

# mybatis-plus配置:
mybatis-plus:
  configuration:
    # 控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭打印sql语句
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 解决查询返回结果含null没有对应字段值问题
    call-setters-on-nulls: true
    # 配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
  # 配置扫描xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.xwl.*.entity
  global-config:
    banner: true
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# pagehelper分页插件配置
pagehelper:
  # 指定分页插件使用哪种方言
  helper-dialect: mysql
  # 在分页查询时进行 count 查询，默认值true
  row-bounds-with-count: true
  # 用户输入的页数不在合法范围能够正确的响应到正确的结果页面, pageNum<=0 会查询第一页, pageNum>总页数 会查询最后一页，默认值true
  reasonable: true

mybatis-helper:
  # 加解密
  crypto:
#    enabled: true
    # 是否开启加解密日志（默认false），开启后info会记录加解密详情
    enable-detail-log: true
    # 加密方式（默认SM4）
    mode: SM4
    # 参数加密前缀（默认enc_，@Param注解value前缀，如@Param("enc_username") String username，表示username需要加密）
    param-prefix: enc_
    # 加解密类全类名（默认com.xwl.mybatishelper.service.impl.DefaultCryptoImpl）
    class-name: com.xwl.mybatishelper.service.impl.DefaultCryptoImpl
#    class-name: com.xwl.mybatishelper.mybatisplus.crypto.CryptoImpl
    # SM4对称加密密钥（必须为随机16位字符串）
    key: a3deb145671dd04e
#    key: JEF8U9WHKWEFS5KD
    # SM2非对称加密公钥
    publicKey: 3059301306072a8648ce3d020106082a811ccf5501822d03420004e6d02503196bda21356390f43e324aa9cb42dbe64204ac4d9e1652fe055e4636702f84f376a54af81ca165d355f3e68d137702b9c715b4ecf70d50b65d9d6e78
    # SM2非对称加密私钥
    privateKey: 308193020100301306072a8648ce3d020106082a811ccf5501822d047930770201010420169d98f96e7a3deb145671dd04eefdf54b3c2196ca5569b5fb96a9ff5abe957da00a06082a811ccf5501822da14403420004e6d02503196bda21356390f43e324aa9cb42dbe64204ac4d9e1652fe055e4636702f84f376a54af81ca165d355f3e68d137702b9c715b4ecf70d50b65d9d6e78
  # 完整性保护
  integrity:
    # 是否开启完整性保护值计算日志（默认false），开启后info会记录完整性保护值计算日志
    enable-detail-log: true
    mode: MD5
    # 完整性保护计算类全类名
    class-name: com.xwl.mybatishelper.service.impl.DefaultIntegrityImpl
  # 脱敏
  desensitized:
    # 是否开启脱敏日志（默认false），开启后info会记录加脱敏详情
    enable-detail-log: true
    # 填充符号
    replacement: '*'
    # 脱敏类全类名
    class-name: com.xwl.mybatishelper.service.impl.DefaultDesensitizedImpl
